### PR TITLE
Add AppVeyor CI/CD

### PR DESCRIPTION
**Pull request by EwoutH**
This PR adds continuous integration & delivery with AppVeyor. SVT-HEVC gets build with Microsoft Visual Studio 2017 and Yasm 1.3.0. AppVeyor publishes `SvtHevcEnc.dll`, `SvtHevcEnc.exp`, `SvtHevcEnc.lib`, `SvtHevcEncApp.exe` and `SvtHevcEncSimpleApp.exe` in the Artifacts tab ([example](https://ci.appveyor.com/project/EwoutH/svt-hevc/builds/22122388/artifacts)).

AppVeyor needs to be enabled on the [GitHub Marketplace](https://github.com/marketplace/appveyor) or on [ci.AppVeyor.com](https://ci.appveyor.com/project/OpenVisualCloud/SVT-HEVC).

When enabled, AppVeyor publishes the artifacts with each build. When tagging a new (pre)release, AppVeyor will also upload these files to GitHub, creating a release page [like this](https://github.com/EwoutH/SVT-HEVC/releases/tag/v1.2.1-test1).

To enable uploading to GitHub Releases, a maintainer needs to update this patch with his personal authentication token. You can generate one on https://github.com/settings/tokens/new (select `public_repo` as scope), and then encrypt it with https://ci.appveyor.com/tools/encrypt. Replace the current token on line 21 (after `secure:`) in the `appveyor.yml` file.

### CODE REVIEW

**Comment by EwoutH** [comment]
@tianjunwork @dseah-intel @lijing0010 What do you think? :)

**Comment by EwoutH** [comment]
Can we update the authentication token and merge this?

**Comment by EwoutH** [comment]
@hassount @tianjunwork @dseah-intel @lijing0010 Ping

**Comment by hassount** [comment]
@EwoutH 
we're looking into this. we are planning to move SVT-HEVC under the OpenVisualCloud and so it would make more sense to enable it after the move not before.

**Comment by EwoutH** [comment]
@hassount When is this move planned?

**Comment by EwoutH** [comment]
> @EwoutH
> we're looking into this. we are planning to move SVT-HEVC under the OpenVisualCloud and so it would make more sense to enable it after the move not before.

Since this probably is still going to be a while, can we merge this?

**Comment by 1480c1** [comment]
Please change Travis from org to com.

**Comment by EwoutH** [comment]
> AppVeyor needs to be enabled on the [GitHub Marketplace](https://github.com/marketplace/appveyor) or on [ci.AppVeyor.com](https://ci.appveyor.com/project/OpenVisualCloud/SVT-HEVC).

@tianjunwork Could you look into this?

**Comment by hassount** [comment]
@EwoutH 
sorry for the late response, extremely busy. the move to openvisualcloud is scheduled for next week, we can enable all next week :)

**Pull request merged**
