### PR TITLE
Travis: Rewrite with Windows and properly reflect macOS build failing

### PR DESCRIPTION
**Pull request by 1480c1**
Similar to: <https://github.com/OpenVisualCloud/SVT-AV1/pull/117>
<https://github.com/OpenVisualCloud/SVT-VP9/pull/14>

Adds a MSVC Release build and a Ninja debug build.
The ninja build is allowed to fail, meaning if the final program fails, it will not mark the whole commit as failing.

I put it there because I'm interested in using mingw and ninja in the future, but I don't want to have to do the work that travis does on my own computer every update.

### CODE REVIEW

**Comment by 1480c1** [comment]
If the checks complete, could I just format the yml a bit better? The indention is throwing me off real bad.

**Comment by EwoutH** [comment]
I would suggest removing the MSVC build, since AppVeyor already does exactly that.

The Ninja build job is a nice addition. We could also consider moving the Ninja build to AppVeyor, since Travis is already slower due to the number of jobs (only 4 are executed simultaneous).

**Comment by 1480c1** [comment]
> I would suggest removing the MSVC build, since AppVeyor already does exactly that.
> 
> The Ninja build job is a nice addition. We could also consider moving the Ninja build to AppVeyor, since Travis is already slower due to the number of jobs (only 4 are executed simultaneous).

I see, I did not know that part, I only added it since we had a linux and macOS release build there. I will remove it.

**Comment by 1480c1** [comment]
> The Ninja build job is a nice addition. We could also consider moving the Ninja build to AppVeyor, since Travis is already slower due to the number of jobs (only 4 are executed simultaneous).

I personally would not recommend to move the ninja build to AppVeyor since I do not think that mingw gcc + ninja is an actual supported build configuration right now for any of the SVT-* and usually ends up failing. I have tried mingw clang + ninja, and that seems to work though.

**Comment by 1480c1** [comment]
I'm going to close these until MacOS builds are fixed. I'll reopen when they are.

**Pull request closed without merging**
