### PR TITLE
Cleanup: Convert tabs to spaces and remove trailing spaces

### PR DESCRIPTION
**Pull request by 1480c1**
WIll the patches be okay with the conversion of whitespaces? Mainly about the hashes

Also modified STYLE.md's sed to exclude .git, build,Bin, and png and added a command to append newlines to files if it doesn't have it. I checked the encoder guide and the pictures seem to not be corrupt

### CODE REVIEW

**Comment by 1480c1** [comment]
The style job now passes for tabs, carriage returns, and spaces and final newlines

Should we enforce that now?

**Comment by tianjunwork** [comment]
@1480c1 Thank you for taking the effort to fix the coding style. We intentionally postpone coding style clean up to avoid rebasing of #70. Once it is merge, could you perform clean up again? Thanks.

**Comment by 1480c1** [comment]
Sure!

**Comment by intelmark** [comment]
Can this be updated as it is the remaining PR item for the 1.4 release and now is a good time to make these changes?  There was another PR for cleanup (226) that is a bit older and can be withdrawn.

**Pull request closed without merging**
